### ISSUE TITLE
Router suddenly undefined

### ISSUE THREAD

**Issue by hasalfred** [lighterio/za#6]
✖ TypeError: Cannot read property '/health/api' of undefined
   finish (node_modules/lighter/node_modules/za/lib/Router.js:102:37)
       98|       }
       99|     }
      100| 
      101|     function finish() {
    ➜ 102|       var fn = paths[request.method][url];
      103|       if (fn) {
   next (node_modules/lighter/node_modules/za/lib/Router.js:97:9)
      94|         m[i].call(app, request, response, next);
      95|       }
      96|       else {
    ➜ 97|         finish();
      98|       }
   Class.module.exports.checkRoute (lib/auth.js:263:14)
      261|     // If the route is public, skip authentication.
      262|     if (publicRoutes.test(url)) {
    ➜ 263|       return next();
      264|     }
   next (node_modules/lighter/node_modules/za/lib/Router.js:94:14)
      93|       if (++i < n) {
    ➜ 94|         m[i].call(app, request, response, next);
      95|       }
   Server.Router.serve (node_modules/lighter/node_modules/za/lib/Router.js:139:5)
    ➜ 139|     next();
   Server.EventEmitter.emit (events.js:98:17)
   HTTPParser.parser.onIncoming (http.js:2108:12)
   HTTPParser.parserOnHeadersComplete [as onHeadersComplete](http.js:121:23)
   Socket.socket.ondata (http.js:1966:22)
   TCP.onread (net.js:525:27)

**Comment by zerious** [comment]
This was fixed by adding HEAD method, etc.
